package io.kcg.sir.application;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.kcg.sir.application.api.ConflictPolicy;
import io.kcg.sir.application.api.ExecutionDiagnostic;
import io.kcg.sir.application.api.ToolchainApplication;
import io.kcg.sir.application.api.ToolchainRequest;
import io.kcg.sir.application.api.ToolchainResult;
import io.kcg.sir.application.internal.SirCompiler;
import io.kcg.sir.application.internal.bundle.BaselineBuilder;
import io.kcg.sir.application.internal.bundle.BaselineManifestEntry;
import io.kcg.sir.change.api.ChangeBaseRevision;
import io.kcg.sir.change.api.RenameAnalysis;
import io.kcg.sir.change.api.RenamePlan;
import io.kcg.sir.change.api.RenamePlanRequest;
import io.kcg.sir.change.api.RenamePlanningInput;
import io.kcg.sir.change.api.RenamePlanner;
import io.kcg.sir.change.api.RenameRevisionSnapshot;
import io.kcg.sir.change.api.RenameSourceSnapshot;
import io.kcg.sir.projectgraph.api.ProjectGraph;
import io.kcg.sir.projectgraph.api.ProjectGraphCanonicalFormatVersion;
import io.kcg.sir.semantic.api.NormalizedSemanticModel;
import io.kcg.sir.semantic.model.NormalizedCapability;
import io.kcg.sir.semantic.model.NormalizedDeclaration;
import io.kcg.sir.semantic.symbol.SymbolId;
import io.kcg.sir.source.SourceId;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * The real Q16 rename fixture, shared by the Q17 plan-binding and pre-flight tests.
 *
 * <p>Everything a seam-A test compares against comes out of the real pipeline: the baseline and the
 * candidate are generated by {@link ToolchainApplication} into their own roots, recompiled in memory
 * by {@link SirCompiler}, and their manifests are built by {@link BaselineBuilder#buildManifest} -
 * the same function {@link BaselineBuilder#build} uses for the Bundle descriptor a registered
 * baseline carries. Nothing here is hand-written except the candidate's rename itself.
 *
 * <p>Each revision cross-checks its own manifest against the tree the toolchain wrote, so a manifest
 * that has drifted from the disk cannot be used as evidence by accident.
 */
final class RenamePreflightTestSupport {

    /** The Q16 fixture: one capability with a declared id plus one bystander capability. */
    static final SourceId SOURCE_ID = SourceId.of("rename-course-search.sir");
    static final String BASE_NAME = "SearchCourseEnrollments";
    static final String CANDIDATE_NAME = "SearchEnrollments";
    static final String DECLARED_CAPABILITY_ID = "search-course-enrollments";

    private static final String RESOURCE = "valid/rename-course-search.sir";
    private static final String BASE_SOURCE = resource();
    /** The same edit the Q16 work order measures: the declared id is kept, the name changes. */
    private static final String CANDIDATE_SOURCE = BASE_SOURCE.replace(BASE_NAME, CANDIDATE_NAME);

    private RenamePreflightTestSupport() {
    }

    static String baseSource() {
        return BASE_SOURCE;
    }

    static String candidateSource() {
        return CANDIDATE_SOURCE;
    }

    /** One real revision: its generated tree on disk, its graph, its model and its Bundle manifest. */
    record Revision(
            Path root,
            ProjectGraph graph,
            NormalizedSemanticModel model,
            RenameSourceSnapshot source,
            List<BaselineManifestEntry> manifest) {

        RenameRevisionSnapshot snapshot() {
            return new RenameRevisionSnapshot(graph, source);
        }

        Map<String, BaselineManifestEntry> manifestByPath() {
            return byPath(manifest);
        }
    }

    static Revision base(Path tempDir) throws IOException {
        return revision(tempDir, "baseline", BASE_SOURCE);
    }

    static Revision candidate(Path tempDir) throws IOException {
        return revision(tempDir, "candidate", CANDIDATE_SOURCE);
    }

    /** The verified Q16 plan for baseline to candidate, over the real revisions. */
    static RenamePlan plan(Revision base, Revision candidate) {
        RenamePlanner planner = new RenamePlanner();
        RenameAnalysis analysis = planner.plan(new RenamePlanningInput(
                base.model(),
                candidate.model(),
                base.snapshot(),
                candidate.snapshot(),
                new RenamePlanRequest(
                        new ChangeBaseRevision(
                                SOURCE_ID,
                                base.source().sha256Hex(),
                                base.graph().version(),
                                base.graph().canonicalDigest(),
                                ProjectGraphCanonicalFormatVersion.V1),
                        declaredCapabilitySymbol(base.model()))));
        RenameAnalysis.Planned planned = analysis instanceof RenameAnalysis.Planned value
                ? value
                : null;
        if (planned == null) {
            throw new AssertionError("the fixture must plan a rename: " + analysis.diagnostics());
        }
        return planned.plan();
    }

    static SymbolId declaredCapabilitySymbol(NormalizedSemanticModel model) {
        for (NormalizedDeclaration declaration : model.declarations()) {
            if (declaration instanceof NormalizedCapability capability
                    && capability.id().value().endsWith("/declared/capability/" + DECLARED_CAPABILITY_ID)) {
                return capability.id();
            }
        }

        throw new AssertionError("no capability with declared id " + DECLARED_CAPABILITY_ID + " in the model");
    }

    static Map<String, BaselineManifestEntry> byPath(List<BaselineManifestEntry> manifest) {
        Map<String, BaselineManifestEntry> byPath = new LinkedHashMap<>();
        for (BaselineManifestEntry entry : manifest) {
            byPath.put(entry.relativePath(), entry);
        }

        return byPath;
    }

    static List<String> pathsOf(List<BaselineManifestEntry> manifest) {
        return manifest.stream().map(BaselineManifestEntry::relativePath).toList();
    }

    /** A byte-for-byte copy of a generated tree, for the tests that mutate the disk. */
    static Path copyTree(Path source, Path target) throws IOException {
        List<Path> paths = new ArrayList<>();
        try (var walk = Files.walk(source)) {
            walk.forEach(paths::add);
        }

        for (Path path : paths) {
            Path relative = source.relativize(path);
            Path destination = target.resolve(relative.toString());
            if (Files.isDirectory(path)) {
                Files.createDirectories(destination);
            } else {
                Files.createDirectories(destination.getParent());
                Files.copy(path, destination);
            }
        }

        return target;
    }

    /** Every regular file under {@code root} as relative path to content digest. */
    static Map<String, String> inventory(Path root) throws IOException {
        Map<String, String> files = new TreeMap<>();
        try (var walk = Files.walk(root)) {
            for (Path path : walk.filter(Files::isRegularFile).toList()) {
                files.put(root.relativize(path).toString().replace('\\', '/'), digestOfFile(path));
            }
        }

        return files;
    }

    static String digestOfFile(Path path) throws IOException {
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(path));
            StringBuilder hex = new StringBuilder(digest.length * 2);
            for (byte value : digest) {
                hex.append(Character.forDigit((value >> 4) & 0xF, 16)).append(Character.forDigit(value & 0xF, 16));
            }

            return hex.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }

    static byte[] bytesOf(Path root, String relativePath) throws IOException {
        return Files.readAllBytes(root.resolve(relativePath));
    }

    static void writeBytes(Path root, String relativePath, byte[] bytes) throws IOException {
        Path target = root.resolve(relativePath);
        Files.createDirectories(target.getParent());
        Files.write(target, bytes);
    }

    private static Revision revision(Path tempDir, String name, String sourceText) throws IOException {
        Path source = tempDir.resolve(name + ".sir").toAbsolutePath();
        Files.writeString(source, sourceText, StandardCharsets.UTF_8);
        Path root = tempDir.resolve(name + "-out").toAbsolutePath();
        ToolchainResult result = new ToolchainApplication().execute(
                new ToolchainRequest(source, SOURCE_ID, root, ConflictPolicy.FAIL_IF_EXISTS));
        if (!(result instanceof ToolchainResult.Success success)) {
            ToolchainResult.Failure failure = (ToolchainResult.Failure) result;
            throw new AssertionError("expected Success but got Failure at " + failure.failedStage()
                    + ": " + failure.diagnostics());
        }

        List<ExecutionDiagnostic> diagnostics = new ArrayList<>();
        SirCompiler.CompiledProject compiled = SirCompiler.compile(sourceText, SOURCE_ID, diagnostics)
                .orElseThrow(() -> new AssertionError("the fixture must compile: " + diagnostics));
        assertEquals(
                success.graph().canonicalDigest(),
                compiled.graph().canonicalDigest(),
                "the tree on disk and the in-memory compile must be the same revision");

        List<BaselineManifestEntry> manifest = BaselineBuilder.buildManifest(compiled.generatedFiles());
        Map<String, String> tree = inventory(root);
        for (BaselineManifestEntry entry : manifest) {
            assertTrue(
                    tree.containsKey(entry.relativePath()),
                    "the manifest is built from the generated files, so every entry is on disk: "
                            + entry.relativePath());
            assertEquals(
                    entry.byteCount(),
                    Files.size(root.resolve(entry.relativePath())),
                    "manifest byte count must be the file on disk: " + entry.relativePath());
            assertEquals(
                    entry.sha256Hex(),
                    tree.get(entry.relativePath()),
                    "manifest digest must be the file on disk: " + entry.relativePath());
        }

        return new Revision(root, compiled.graph(), compiled.semanticModel(),
                RenameSourceSnapshot.of(SOURCE_ID, sourceText), manifest);
    }

    private static String resource() {
        try {
            return ApplicationTestSupport.resource(RESOURCE);
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
    }
}
